version: '3'

services:

  app:
    build: .
    environment: 
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    command: sh -c "npm run dev"
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo-gui
      - mongo
    ports:
      - 5000:3000

  mongo-gui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo

  test:
    build: .
    environment: 
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env.test
    command: sh -c "npm run test"
    volumes:
      - ./src:/app/src
    depends_on:
      - test-mongo

  mongo:
    image: mongo
    restart: always

  test-mongo:
    image: mongo
    restart: always
